version: '3.8'
services:
  db:
    image: postgres:14.9
    restart: always
    container_name: anylistDB
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data